### ISSUE TITLE
To update the release in Open Exchange please

### ISSUE THREAD

**Issue by SergeyMi37** [rcemper/Native-API-for-ObjectScript#2]
To update the release in Open Exchange please.
https://openexchange.intersystems.com/markdown?url=assets%2Fdoc%2Freleases.md
Thanks.

![image](https://user-images.githubusercontent.com/18187317/130123683-352f2075-56c0-484b-8f7c-14cf5025c5e9.png)

**Comment by rcemper** [comment]
done

**Comment by rcemper** [comment]
new version done
